// <auto-generated />
using System;
using CosmosPro.ML.DemandForCast.Engine;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CosmosPro.ML.DemandForCast.Engine.Migrations
{
    [DbContext(typeof(EngineDbContext))]
    partial class EngineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.CargaStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTimeOffset>("DataAgendamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataConclusao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataInicioProcessamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LinhasImportadas")
                        .HasColumnType("bigint");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NomeArquivoOriginal")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "DataAgendamento")
                        .HasDatabaseName("IX_CargasStage_Status_DataAgendamento");

                    b.ToTable("CargasStage", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
